exclude: "^{{cookiecutter\\.project_slug}}/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .bumpversion.cfg
      - id: check-added-large-files
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
