[tool.poetry]
name = "cookiecutter-pypackage"
version = "0.1.0"
description = "Cookiecutter template for a Python package"
license = "BSD-3-Clause"
authors = ["Mike Perov <mishamsk@gmail.com>"]
readme = "README.md"
repository = "https://github.com/mishamsk/cookiecutter-pypackage"
documentation = "https://mishamsk.github.io/cookiecutter-pypackage"
keywords = ['cookiecutter', 'template', 'package']

include = [
  '{{cookiecutter.project_slug}}/**/*',
  'cookiecutter.json',
  'hooks/*'
]

[tool.poetry.dependencies]
python = "^3.10"
cookiecutter = "2.1.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1.2"
pytest-cookies = "^0.6.1"
PyYAML = "^6.0"
mkdocs = "^1.3.1"
mkdocs-material = "^8.3.9"
mkdocs-material-extensions = "^1.0.3"
pytest-cov = "^3.0.0"
tox = "^3.25.1"
mkdocs-include-markdown-plugin = "^3.6.1"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
